# -*- coding: utf-8 -*-
"""S20851.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGUScZ5a0OVnSo7FzeR6BjNehBTmeK9B
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("ai_jobs_market_2025_2026.csv")
df.head()

df.shape
df.info()
df.describe()

df.isnull().sum()

num_cols = [
    'years_of_experience',
    'annual_salary_usd',
    'salary_min_usd',
    'salary_max_usd',
    'ai_salary_premium_pct',
    'demand_score',
    'demand_growth_yoy_pct',
    'benefits_score_10'
]

df_num = df[num_cols]
df_num.describe()

drop_cols = ['job_id', 'job_title', 'city', 'required_skills']
df = df.drop(columns=drop_cols)

import seaborn as sns
import matplotlib.pyplot as plt

num_cols = [
    'years_of_experience',
    'annual_salary_usd',
    'salary_min_usd',
    'salary_max_usd',
    'ai_salary_premium_pct',
    'demand_score',
    'demand_growth_yoy_pct',
    'benefits_score_10'
]

df_num = df[num_cols]

df_num.hist(figsize=(12,8))
plt.show()

for col in df_num.columns:
    plt.figure()
    plt.boxplot(df_num[col])
    plt.title(col)
    plt.show()

import seaborn as sns
plt.figure(figsize=(10,6))
sns.heatmap(df_num.corr(), annot=True)
plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_num)

df_scaled.mean(), df_scaled.std()

from sklearn.decomposition import PCA
import numpy as np

# Apply PCA
pca = PCA()
pca.fit(df_scaled)

# Explained variance
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

import matplotlib.pyplot as plt

plt.plot(np.cumsum(explained_variance), marker='o')
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Scree Plot - Cumulative Variance Explained')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Apply PCA
pca = PCA()
pca.fit(df_scaled)

# Explained variance ratio
explained_variance = pca.explained_variance_ratio_

# Plot scree plot (individual variance)
plt.figure()
plt.plot(range(1, len(explained_variance)+1), explained_variance, marker='o')
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance')
plt.title('Scree Plot (Individual Explained Variance)')
plt.show()

import numpy as np

cumulative_variance = np.cumsum(explained_variance)

plt.figure()
plt.plot(range(1, len(explained_variance)+1), explained_variance, marker='o', label='Individual')
plt.plot(range(1, len(cumulative_variance)+1), cumulative_variance, marker='s', label='Cumulative')

plt.xlabel('Principal Component')
plt.ylabel('Variance Explained')
plt.title('Scree Plot')
plt.legend()
plt.show()

loadings_pca = pd.DataFrame(
    pca.components_.T,
      columns=[f'PC{i+1}' for i in range(len(df_num.columns))],
    index=df_num.columns
)

print("Loadings: ",loadings_pca)

!pip install factor_analyzer
from factor_analyzer.factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_kmo, calculate_bartlett_sphericity

# KMO Test
kmo_all, kmo_model = calculate_kmo(df_num)
print("KMO:", kmo_model)

# Bartlett Test
chi_square_value, p_value = calculate_bartlett_sphericity(df_num)
print("Bartlett Test p-value:", p_value)

from factor_analyzer import FactorAnalyzer

# Fit FA without rotation
fa = FactorAnalyzer(rotation=None)
fa.fit(df_scaled)

# Get eigenvalues
eigenvalues, _ = fa.get_eigenvalues()

print("eigenvalues: ",eigenvalues)

fa = FactorAnalyzer(n_factors=3, rotation='varimax')
fa.fit(df_scaled)

loadings_fa = pd.DataFrame(fa.loadings_,
                           index=num_cols,
                           columns=['Factor1', 'Factor2', 'Factor3'])

print(loadings_fa)

plt.figure()
plt.plot(range(1, len(eigenvalues)+1), eigenvalues, marker='o')
plt.axhline(y=1, linestyle='--')
plt.xlabel('Factor Number')
plt.ylabel('Eigenvalue')
plt.title('Scree Plot (Factor Analysis)')
plt.show()

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Features (numerical variables)
X = df_num

# Target variable
y = df['salary_tier']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Fit LDA model
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

# Predictions
y_pred = lda.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

!pip install bioinfokit

from bioinfokit.analys import stat

# Prepare dataset (numerical + group)
data = df_num.copy()
data['group'] = df['salary_tier']   # target variable

# Run Box's M test
res = stat()

if hasattr(res, 'box_m'):
    res.box_m(df=data, grp_col='group')
    # Print results if the test was run
    print(res.box_m_test)
else:
    print("Error: The 'stat' object from bioinfokit.analys does not have a 'box_m' method.")
    print("This is unexpected for bioinfokit version 2.1.4 and might indicate an issue with the installation or environment.")
    print("Please verify your bioinfokit installation or consider using an alternative method for Box's M test.")

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

# Initialize and fit QDA model
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train, y_train)

# Predictions
y_pred_qda = qda.predict(X_test)

# Accuracy
accuracy_qda = accuracy_score(y_test, y_pred_qda)
print(f"QDA Accuracy: {accuracy_qda}")

# Confusion matrix
cm_qda = confusion_matrix(y_test, y_pred_qda)
print("QDA Confusion Matrix:\n", cm_qda)

from sklearn.metrics import f1_score, recall_score, classification_report

# Calculate and print F1-score and Recall for LDA
f1_lda = f1_score(y_test, y_pred, average='weighted')
recall_lda = recall_score(y_test, y_pred, average='weighted')
print(f"LDA F1-score (weighted): {f1_lda:.4f}")
print(f"LDA Recall (weighted): {recall_lda:.4f}")

# Calculate and print F1-score and Recall for QDA
f1_qda = f1_score(y_test, y_pred_qda, average='weighted')
recall_qda = recall_score(y_test, y_pred_qda, average='weighted')
print(f"QDA F1-score (weighted): {f1_qda:.4f}")
print(f"QDA Recall (weighted): {recall_qda:.4f}")

# Print classification report for LDA
print("\nLDA Classification Report:\n")
print(classification_report(y_test, y_pred))

# Print classification report for QDA
print("\nQDA Classification Report:\n")
print(classification_report(y_test, y_pred_qda))

import matplotlib.pyplot as plt
import seaborn as sns

# Set up the matplotlib figure and axes for two subplots
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Plot Confusion Matrix for LDA
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=lda.classes_, yticklabels=lda.classes_)
axes[0].set_title('LDA Confusion Matrix')
axes[0].set_xlabel('Predicted Label')
axes[0].set_ylabel('True Label')

# Plot Confusion Matrix for QDA
sns.heatmap(cm_qda, annot=True, fmt='d', cmap='Greens', ax=axes[1],
            xticklabels=qda.classes_, yticklabels=qda.classes_)
axes[1].set_title('QDA Confusion Matrix')
axes[1].set_xlabel('Predicted Label')
axes[1].set_ylabel('True Label')

plt.tight_layout()
plt.show()